// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Prisma 7 move a config de seed do package.json ("prisma.seed") para cá.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // O CLI usa a conexao direta para migrations/seed; DATABASE_URL e fallback local.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
